In [18]:
from tensorflow import keras
import tensorflow as tf
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv('../data/df.csv')
df

,aX,aY,aZ,gX,gY,gZ,little,ring,middle,index,thumb,number
0,0.03,0.91,0.40,2.14,-3.23,-0.92,409,458,189,240,199,0
1,0.02,0.91,0.40,0.73,-0.79,-1.59,416,455,192,243,195,0
2,0.01,0.91,0.41,-1.59,-1.83,-5.62,409,451,190,242,197,0
3,0.00,0.89,0.43,3.42,-4.70,-1.10,413,451,190,249,202,0
4,0.05,0.91,0.38,-1.46,-1.28,-0.06,410,458,190,243,199,0
...,...,...,...,...,...,...,...,...,...,...,...,...
61983,0.38,0.79,0.47,1.16,-0.73,-2.99,412,397,265,448,358,29
61984,0.37,0.81,0.49,9.70,-8.61,9.83,410,397,268,447,360,29
61985,0.42,0.79,0.43,3.11,-2.32,-2.20,408,396,267,450,359,29
61986,0.42,0.80,0.44,1.65,-3.36,-2.75,410,401,264,454,359,29
61987,0.41,0.79,0.44,-1.46,-2.01,-3.85,408,395,267,448,361,29

In [20]:
np.random.seed(42)
dfs = df.copy()

# shuffling í•˜ê³  index reset
dfs = dfs.sample(frac = 1).reset_index(drop=True)
dfs

,aX,aY,aZ,gX,gY,gZ,little,ring,middle,index,thumb,number
0,-0.26,-0.93,-0.21,0.98,-2.62,-2.93,402,265,203,449,305,24
1,0.32,0.92,0.25,6.04,0.43,-0.92,427,472,240,299,253,0
2,0.96,-0.20,0.29,1.46,-2.50,-1.95,344,453,408,473,235,3
3,0.88,-0.36,-0.31,1.53,-2.75,-2.20,379,279,199,444,349,28
4,0.11,0.79,0.63,0.98,-9.52,3.48,239,308,390,461,338,21
...,...,...,...,...,...,...,...,...,...,...,...,...
61983,0.92,-0.39,0.00,3.23,3.78,-4.82,381,287,238,473,326,26
61984,0.09,-0.99,0.16,1.22,-4.27,-2.20,248,249,217,451,309,18
61985,0.27,0.93,0.27,-0.73,-2.81,-2.99,421,470,245,295,254,0
61986,-0.12,-0.98,-0.12,0.31,-3.91,-1.83,339,337,291,412,459,7
61987,0.90,-0.33,0.31,1.77,-1.34,-2.62,442,236,406,448,306,27

In [21]:
# X,y ë‚˜ëˆ„ê¸°
data = dfs.copy()
X = data.drop("number", axis =1)
X

         aX    aY    aZ    gX    gY    gZ  little  ring  middle  index  thumb
0     -0.26 -0.93 -0.21  0.98 -2.62 -2.93     402   265     203    449    305
1      0.32  0.92  0.25  6.04  0.43 -0.92     427   472     240    299    253
2      0.96 -0.20  0.29  1.46 -2.50 -1.95     344   453     408    473    235
3      0.88 -0.36 -0.31  1.53 -2.75 -2.20     379   279     199    444    349
4      0.11  0.79  0.63  0.98 -9.52  3.48     239   308     390    461    338
...     ...   ...   ...   ...   ...   ...     ...   ...     ...    ...    ...
61983  0.92 -0.39  0.00  3.23  3.78 -4.82     381   287     238    473    326
61984  0.09 -0.99  0.16  1.22 -4.27 -2.20     248   249     217    451    309
61985  0.27  0.93  0.27 -0.73 -2.81 -2.99     421   470     245    295    254
61986 -0.12 -0.98 -0.12  0.31 -3.91 -1.83     339   337     291    412    459
61987  0.90 -0.33  0.31  1.77 -1.34 -2.62     442   236     406    448    306

[61988 rows x 11 columns]

In [22]:
y = dfs["number"].copy()
y

0        24
1         0
2         3
3        28
4        21
         ..
61983    26
61984    18
61985     0
61986     7
61987    27
Name: number, Length: 61988, dtype: int64

In [23]:
x_test, x_train = X[:18000], X[18000:]
y_test, y_train = y[:18000], y[18000:]
x_train

         aX    aY    aZ    gX    gY    gZ  little  ring  middle  index  thumb
18000  0.29  0.91  0.29  1.04 -2.14 -2.44     330   461     385    268    219
18001  0.78 -0.46 -0.22  8.30  1.28 -1.10     256   301     245    473    430
18002  0.93 -0.34  0.17  2.56 -3.17 -1.65     423   358     249    460    359
18003  0.92 -0.36 -0.14  0.61 -2.69 -3.36     400   469     245    311    236
18004  0.89 -0.38  0.31 -0.18 -2.75 -2.01     415   263     386    459    325
...     ...   ...   ...   ...   ...   ...     ...   ...     ...    ...    ...
61983  0.92 -0.39  0.00  3.23  3.78 -4.82     381   287     238    473    326
61984  0.09 -0.99  0.16  1.22 -4.27 -2.20     248   249     217    451    309
61985  0.27  0.93  0.27 -0.73 -2.81 -2.99     421   470     245    295    254
61986 -0.12 -0.98 -0.12  0.31 -3.91 -1.83     339   337     291    412    459
61987  0.90 -0.33  0.31  1.77 -1.34 -2.62     442   236     406    448    306

[43988 rows x 11 columns]

In [24]:
tf.random.set_seed(42)
np.random.seed(42)

model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[11,]),
    keras.layers.Dense(300, kernel_initializer="he_normal"),
    keras.layers.LeakyReLU(),
    keras.layers.Dense(300, kernel_initializer="he_normal"),
    keras.layers.LeakyReLU(),
    keras.layers.Dense(30, activation="softmax")
])

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 flatten_1 (Flatten)         (None, 11)                0

 dense_3 (Dense)             (None, 300)               3600

 leaky_re_lu_2 (LeakyReLU)   (None, 300)               0

 dense_4 (Dense)             (None, 300)               90300

 leaky_re_lu_3 (LeakyReLU)   (None, 300)               0

 dense_5 (Dense)             (None, 30)                9030

=================================================================
Total params: 102,930
Trainable params: 102,930
Non-trainable params: 0
_________________________________________________________________

In [26]:
model.compile(loss="sparse_categorical_crossentropy",
              optimizer=keras.optimizers.SGD(learning_rate=1e-3),
              metrics=["accuracy"])

In [27]:
history = model.fit(x_train, y_train, epochs=100)

Epoch 1/100
1375/1375 [==============================] - 8s 5ms/step - loss: 71.2835 - accuracy: 0.5320
Epoch 2/100
1375/1375 [==============================] - 7s 5ms/step - loss: 5.6583 - accuracy: 0.6608
Epoch 3/100
1375/1375 [==============================] - 7s 5ms/step - loss: 3.4922 - accuracy: 0.7228
Epoch 4/100
1375/1375 [==============================] - 7s 5ms/step - loss: 2.6806 - accuracy: 0.7501
Epoch 5/100
1375/1375 [==============================] - 7s 5ms/step - loss: 2.2722 - accuracy: 0.7762
Epoch 6/100
1375/1375 [==============================] - 7s 5ms/step - loss: 1.8274 - accuracy: 0.7991
Epoch 7/100
1375/1375 [==============================] - 7s 5ms/step - loss: 1.6086 - accuracy: 0.8115
Epoch 8/100
1375/1375 [==============================] - 7s 5ms/step - loss: 1.5008 - accuracy: 0.8248
Epoch 9/100
1375/1375 [==============================] - 7s 5ms/step - loss: 1.3602 - accuracy: 0.8314
Epoch 10/100
1375/1375 [==============================] - 7s 5ms/step - loss: 1.3128 - accuracy: 0.8380
Epoch 11/100
1375/1375 [==============================] - 7s 5ms/step - loss: 1.1824 - accuracy: 0.8495
Epoch 12/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.9907 - accuracy: 0.8619
Epoch 13/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.9580 - accuracy: 0.8626
Epoch 14/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.8467 - accuracy: 0.8734
Epoch 15/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.9235 - accuracy: 0.8694
Epoch 16/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.7816 - accuracy: 0.8781
Epoch 17/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.8350 - accuracy: 0.8729
Epoch 18/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.7206 - accuracy: 0.8846
Epoch 19/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.7027 - accuracy: 0.8840
Epoch 20/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.6724 - accuracy: 0.8931
Epoch 21/100
1375/1375 [==============================] - 8s 6ms/step - loss: 0.6859 - accuracy: 0.8892
Epoch 22/100
1375/1375 [==============================] - 8s 5ms/step - loss: 0.6377 - accuracy: 0.8968
Epoch 23/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.6087 - accuracy: 0.9005
Epoch 24/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.6243 - accuracy: 0.8986
Epoch 25/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.5267 - accuracy: 0.9061
Epoch 26/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.5490 - accuracy: 0.9041
Epoch 27/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.5105 - accuracy: 0.9088
Epoch 28/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.5117 - accuracy: 0.9091
Epoch 29/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.4720 - accuracy: 0.9138
Epoch 30/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.4608 - accuracy: 0.9149
Epoch 31/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.4543 - accuracy: 0.9151
Epoch 32/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.4765 - accuracy: 0.9155
Epoch 33/100
1375/1375 [==============================] - 7s 5ms/step - loss: 0.4391 - accuracy: 0.9179
Epoch 34/100
1375/1375 [==============================] - 5s 4ms/step - loss: 0.4226 - accuracy: 0.9191
Epoch 35/100
1375/1375 [==============================] - 2s 2ms/step - loss: 0.4361 - accuracy: 0.9181
Epoch 36/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.4349 - accuracy: 0.9176
Epoch 37/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.4298 - accuracy: 0.9186
Epoch 38/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.4619 - accuracy: 0.9184
Epoch 39/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3627 - accuracy: 0.9248
Epoch 40/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.4372 - accuracy: 0.9178
Epoch 41/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3979 - accuracy: 0.9216
Epoch 42/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3844 - accuracy: 0.9245
Epoch 43/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3570 - accuracy: 0.9288
Epoch 44/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3199 - accuracy: 0.9346
Epoch 45/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3824 - accuracy: 0.9237
Epoch 46/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3467 - accuracy: 0.9280
Epoch 47/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3130 - accuracy: 0.9331
Epoch 48/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3280 - accuracy: 0.9318
Epoch 49/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3341 - accuracy: 0.9307
Epoch 50/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3617 - accuracy: 0.9269
Epoch 51/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3070 - accuracy: 0.9350
Epoch 52/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3338 - accuracy: 0.9309
Epoch 53/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3466 - accuracy: 0.9296
Epoch 54/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3283 - accuracy: 0.9323
Epoch 55/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3302 - accuracy: 0.9300
Epoch 56/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3059 - accuracy: 0.9363
Epoch 57/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3945 - accuracy: 0.9260
Epoch 58/100
1375/1375 [==============================] - 3s 3ms/step - loss: 0.3201 - accuracy: 0.9328
Epoch 59/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3265 - accuracy: 0.9327
Epoch 60/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2844 - accuracy: 0.9373
Epoch 61/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2995 - accuracy: 0.9381
Epoch 62/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2720 - accuracy: 0.9415
Epoch 63/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.3134 - accuracy: 0.9336
Epoch 64/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2821 - accuracy: 0.9393
Epoch 65/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2565 - accuracy: 0.9410
Epoch 66/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2623 - accuracy: 0.9410
Epoch 67/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2822 - accuracy: 0.9374
Epoch 68/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2868 - accuracy: 0.9371
Epoch 69/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2630 - accuracy: 0.9416
Epoch 70/100
1375/1375 [==============================] - 2s 2ms/step - loss: 0.2585 - accuracy: 0.9418
Epoch 71/100
1375/1375 [==============================] - 2s 2ms/step - loss: 0.2590 - accuracy: 0.9425
Epoch 72/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2624 - accuracy: 0.9428
Epoch 73/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2657 - accuracy: 0.9428
Epoch 74/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2676 - accuracy: 0.9407
Epoch 75/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2567 - accuracy: 0.9427
Epoch 76/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2472 - accuracy: 0.9437
Epoch 77/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2477 - accuracy: 0.9439
Epoch 78/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2516 - accuracy: 0.9399
Epoch 79/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2322 - accuracy: 0.9462
Epoch 80/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2649 - accuracy: 0.9410
Epoch 81/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2609 - accuracy: 0.9435
Epoch 82/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2230 - accuracy: 0.9477
Epoch 83/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2379 - accuracy: 0.9441
Epoch 84/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2412 - accuracy: 0.9443
Epoch 85/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2419 - accuracy: 0.9450
Epoch 86/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2384 - accuracy: 0.9450
Epoch 87/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2097 - accuracy: 0.9491
Epoch 88/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2365 - accuracy: 0.9451
Epoch 89/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2175 - accuracy: 0.9484
Epoch 90/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2056 - accuracy: 0.9500
Epoch 91/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2158 - accuracy: 0.9489
Epoch 92/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2220 - accuracy: 0.9472
Epoch 93/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2218 - accuracy: 0.9461
Epoch 94/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2070 - accuracy: 0.9507
Epoch 95/100
1375/1375 [==============================] - 3s 2ms/step - loss: 0.2236 - accuracy: 0.9466
Epoch 96/100
1375/1375 [==============================] - 4s 3ms/step - loss: 0.2095 - accuracy: 0.9498
Epoch 97/100
1375/1375 [==============================] - 3s 3ms/step - loss: 0.2172 - accuracy: 0.9482
Epoch 98/100
1375/1375 [==============================] - 4s 3ms/step - loss: 0.2070 - accuracy: 0.9506
Epoch 99/100
1375/1375 [==============================] - 4s 3ms/step - loss: 0.2368 - accuracy: 0.9468
Epoch 100/100
1375/1375 [==============================] - 4s 3ms/step - loss: 0.2180 - accuracy: 0.9496

In [28]:
val_loss, val_accuracy = model.evaluate(x_test, y_test)
print(val_accuracy)

563/563 [==============================] - 1s 2ms/step - loss: 0.2527 - accuracy: 0.9496
0.9496111273765564

In [60]:
model.save("model_1.h5")

In [61]:
model = tf.keras.models.load_model('model_1.h5')

In [62]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)

In [63]:
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
converter.target_spec.supported_types = [tf.float16]
converter.optimizations = [tf.lite.Optimize.DEFAULT]

In [64]:
tflite_model = converter.convert()

INFO:tensorflow:Assets written to: C:\Users\ddang\AppData\Local\Temp\tmpa6hoa06d\assets

INFO:tensorflow:Assets written to: C:\Users\ddang\AppData\Local\Temp\tmpa6hoa06d\assets
WARNING:absl:Buffer deduplication procedure will be skipped when flatbuffer library is not properly loaded

In [66]:
with open('model.tflite', 'wb') as f:
    f.write(tflite_model)