In [4]:
from tensorflow import keras
import tensorflow as tf
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('../../data/final_data.csv')
df

,aX,aY,aZ,gX,gY,gZ,little,ring,middle,index,thumb,number
0,0.03,0.91,0.40,2.14,-3.23,-0.92,409,458,189,240,199,0
1,0.02,0.91,0.40,0.73,-0.79,-1.59,416,455,192,243,195,0
2,0.01,0.91,0.41,-1.59,-1.83,-5.62,409,451,190,242,197,0
3,0.00,0.89,0.43,3.42,-4.70,-1.10,413,451,190,249,202,0
4,0.05,0.91,0.38,-1.46,-1.28,-0.06,410,458,190,243,199,0
...,...,...,...,...,...,...,...,...,...,...,...,...
154995,-0.17,-0.98,-0.03,0.06,-2.32,-2.93,263,317,226,247,202,12
154996,-0.15,-0.98,-0.02,1.04,-2.81,-2.99,259,317,215,251,203,12
154997,-0.16,-0.98,-0.03,1.10,-4.09,-2.99,260,318,219,248,206,12
154998,-0.16,-0.98,-0.01,1.16,-2.81,-2.69,257,319,222,252,206,12
154999,-0.16,-0.98,-0.02,0.79,-2.87,-3.30,261,320,224,252,201,12

In [6]:
np.random.seed(42)
dfs = df.copy()

# shuffling í•˜ê³  index reset
dfs = dfs.sample(frac = 1).reset_index(drop=True)
dfs

,aX,aY,aZ,gX,gY,gZ,little,ring,middle,index,thumb,number
0,0.48,0.85,0.23,-0.98,-0.67,-4.46,404,305,238,458,331,29
1,0.98,-0.18,-0.01,-1.34,-4.52,-0.79,216,472,402,476,297,3
2,0.37,0.87,0.34,0.00,-3.23,-3.05,287,255,402,457,321,21
3,0.16,0.92,0.36,0.73,-3.85,-2.62,322,408,204,247,389,29
4,-0.30,-0.87,-0.35,1.22,-4.33,-2.50,282,231,212,276,422,23
...,...,...,...,...,...,...,...,...,...,...,...,...
154995,-0.37,-0.83,-0.38,0.92,-3.11,-2.87,286,230,214,290,371,23
154996,-0.06,-0.99,0.03,0.55,-2.62,-2.93,331,463,371,302,245,15
154997,-0.34,-0.88,-0.28,0.79,-2.99,-2.87,319,464,371,262,386,25
154998,-0.02,-0.96,-0.24,1.28,-2.44,-2.26,322,440,197,255,370,30
154999,-0.07,0.96,0.27,-0.43,-3.36,-2.99,341,439,203,274,203,20

In [8]:
# X,y ë‚˜ëˆ„ê¸°
data = dfs.copy()
X = data.drop("number", axis =1)
X

          aX    aY    aZ    gX    gY    gZ  little  ring  middle  index  thumb
0       0.48  0.85  0.23 -0.98 -0.67 -4.46     404   305     238    458    331
1       0.98 -0.18 -0.01 -1.34 -4.52 -0.79     216   472     402    476    297
2       0.37  0.87  0.34  0.00 -3.23 -3.05     287   255     402    457    321
3       0.16  0.92  0.36  0.73 -3.85 -2.62     322   408     204    247    389
4      -0.30 -0.87 -0.35  1.22 -4.33 -2.50     282   231     212    276    422
...      ...   ...   ...   ...   ...   ...     ...   ...     ...    ...    ...
154995 -0.37 -0.83 -0.38  0.92 -3.11 -2.87     286   230     214    290    371
154996 -0.06 -0.99  0.03  0.55 -2.62 -2.93     331   463     371    302    245
154997 -0.34 -0.88 -0.28  0.79 -2.99 -2.87     319   464     371    262    386
154998 -0.02 -0.96 -0.24  1.28 -2.44 -2.26     322   440     197    255    370
154999 -0.07  0.96  0.27 -0.43 -3.36 -2.99     341   439     203    274    203

[155000 rows x 11 columns]

In [7]:
y = dfs["number"].copy()
y

0         29
1          3
2         21
3         29
4         23
          ..
154995    23
154996    15
154997    25
154998    30
154999    20
Name: number, Length: 155000, dtype: int64

In [9]:
X

          aX    aY    aZ    gX    gY    gZ  little  ring  middle  index  thumb
0       0.48  0.85  0.23 -0.98 -0.67 -4.46     404   305     238    458    331
1       0.98 -0.18 -0.01 -1.34 -4.52 -0.79     216   472     402    476    297
2       0.37  0.87  0.34  0.00 -3.23 -3.05     287   255     402    457    321
3       0.16  0.92  0.36  0.73 -3.85 -2.62     322   408     204    247    389
4      -0.30 -0.87 -0.35  1.22 -4.33 -2.50     282   231     212    276    422
...      ...   ...   ...   ...   ...   ...     ...   ...     ...    ...    ...
154995 -0.37 -0.83 -0.38  0.92 -3.11 -2.87     286   230     214    290    371
154996 -0.06 -0.99  0.03  0.55 -2.62 -2.93     331   463     371    302    245
154997 -0.34 -0.88 -0.28  0.79 -2.99 -2.87     319   464     371    262    386
154998 -0.02 -0.96 -0.24  1.28 -2.44 -2.26     322   440     197    255    370
154999 -0.07  0.96  0.27 -0.43 -3.36 -2.99     341   439     203    274    203

[155000 rows x 11 columns]

In [10]:
y

0         29
1          3
2         21
3         29
4         23
          ..
154995    23
154996    15
154997    25
154998    30
154999    20
Name: number, Length: 155000, dtype: int64

In [11]:
tf.random.set_seed(42)
np.random.seed(42)

model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[11,]),
    keras.layers.Dense(300, kernel_initializer="lecun_normal", activation = 'selu'),
    keras.layers.Dense(300, kernel_initializer="lecun_normal", activation = 'selu'),
    keras.layers.Dense(31, activation="softmax")
])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 flatten (Flatten)           (None, 11)                0

 dense (Dense)               (None, 300)               3600

 dense_1 (Dense)             (None, 300)               90300

 dense_2 (Dense)             (None, 31)                9331

=================================================================
Total params: 103,231
Trainable params: 103,231
Non-trainable params: 0
_________________________________________________________________

In [13]:
model.compile(loss="sparse_categorical_crossentropy",
              optimizer='adam',
              metrics=["accuracy"])

In [14]:
lr_schedular = keras.callbacks.ReduceLROnPlateau(patience=10, factor = 0.5)

In [15]:
history = model.fit(X, y, epochs=100)

Epoch 1/100
4844/4844 [==============================] - 55s 10ms/step - loss: 2.7786 - accuracy: 0.6280
Epoch 2/100
4844/4844 [==============================] - 51s 11ms/step - loss: 0.3820 - accuracy: 0.8492
Epoch 3/100
4844/4844 [==============================] - 59s 12ms/step - loss: 0.2628 - accuracy: 0.9016
Epoch 4/100
4844/4844 [==============================] - 51s 11ms/step - loss: 0.2239 - accuracy: 0.9208
Epoch 5/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.1898 - accuracy: 0.9343
Epoch 6/100
4844/4844 [==============================] - 52s 11ms/step - loss: 0.1797 - accuracy: 0.9395
Epoch 7/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.1649 - accuracy: 0.9443
Epoch 8/100
4844/4844 [==============================] - 52s 11ms/step - loss: 0.1541 - accuracy: 0.9486
Epoch 9/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.1465 - accuracy: 0.9516
Epoch 10/100
4844/4844 [==============================] - 51s 10ms/step - loss: 0.1508 - accuracy: 0.9521
Epoch 11/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.1420 - accuracy: 0.9553
Epoch 12/100
4844/4844 [==============================] - 48s 10ms/step - loss: 0.1315 - accuracy: 0.9587
Epoch 13/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.1344 - accuracy: 0.9586
Epoch 14/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.1258 - accuracy: 0.9613
Epoch 15/100
4844/4844 [==============================] - 52s 11ms/step - loss: 0.1300 - accuracy: 0.9603
Epoch 16/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.1199 - accuracy: 0.9634
Epoch 17/100
4844/4844 [==============================] - 48s 10ms/step - loss: 0.1158 - accuracy: 0.9651
Epoch 18/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.1164 - accuracy: 0.9650
Epoch 19/100
4844/4844 [==============================] - 48s 10ms/step - loss: 0.1176 - accuracy: 0.9650
Epoch 20/100
4844/4844 [==============================] - 46s 10ms/step - loss: 0.1119 - accuracy: 0.9666
Epoch 21/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.1114 - accuracy: 0.9675
Epoch 22/100
4844/4844 [==============================] - 46s 9ms/step - loss: 0.1106 - accuracy: 0.9683
Epoch 23/100
4844/4844 [==============================] - 47s 10ms/step - loss: 0.1104 - accuracy: 0.9686
Epoch 24/100
4844/4844 [==============================] - 52s 11ms/step - loss: 0.1070 - accuracy: 0.9701
Epoch 25/100
4844/4844 [==============================] - 51s 11ms/step - loss: 0.1097 - accuracy: 0.9694
Epoch 26/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.1008 - accuracy: 0.9718
Epoch 27/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.1024 - accuracy: 0.9718
Epoch 28/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.0985 - accuracy: 0.9727
Epoch 29/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0983 - accuracy: 0.9721
Epoch 30/100
4844/4844 [==============================] - 52s 11ms/step - loss: 0.0977 - accuracy: 0.9729
Epoch 31/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0975 - accuracy: 0.9736
Epoch 32/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.1044 - accuracy: 0.9723
Epoch 33/100
4844/4844 [==============================] - 48s 10ms/step - loss: 0.1005 - accuracy: 0.9732
Epoch 34/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0983 - accuracy: 0.9736
Epoch 35/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0984 - accuracy: 0.9742
Epoch 36/100
4844/4844 [==============================] - 48s 10ms/step - loss: 0.0974 - accuracy: 0.9746
Epoch 37/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.0993 - accuracy: 0.9747
Epoch 38/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.0950 - accuracy: 0.9749
Epoch 39/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.0956 - accuracy: 0.9748
Epoch 40/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0963 - accuracy: 0.9754
Epoch 41/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.0951 - accuracy: 0.9755
Epoch 42/100
4844/4844 [==============================] - 48s 10ms/step - loss: 0.0950 - accuracy: 0.9753
Epoch 43/100
4844/4844 [==============================] - 51s 10ms/step - loss: 0.0933 - accuracy: 0.9756
Epoch 44/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0943 - accuracy: 0.9758
Epoch 45/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.0936 - accuracy: 0.9764
Epoch 46/100
4844/4844 [==============================] - 48s 10ms/step - loss: 0.0923 - accuracy: 0.9760
Epoch 47/100
4844/4844 [==============================] - 47s 10ms/step - loss: 0.0935 - accuracy: 0.9758
Epoch 48/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0898 - accuracy: 0.9769
Epoch 49/100
4844/4844 [==============================] - 51s 11ms/step - loss: 0.0916 - accuracy: 0.9777
Epoch 50/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.0893 - accuracy: 0.9774
Epoch 51/100
4844/4844 [==============================] - 51s 10ms/step - loss: 0.0927 - accuracy: 0.9770
Epoch 52/100
4844/4844 [==============================] - 51s 11ms/step - loss: 0.0888 - accuracy: 0.9773
Epoch 53/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0860 - accuracy: 0.9786
Epoch 54/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0910 - accuracy: 0.9777
Epoch 55/100
4844/4844 [==============================] - 52s 11ms/step - loss: 0.0912 - accuracy: 0.9777
Epoch 56/100
4844/4844 [==============================] - 48s 10ms/step - loss: 0.0907 - accuracy: 0.9774
Epoch 57/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0905 - accuracy: 0.9775
Epoch 58/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.0895 - accuracy: 0.9780
Epoch 59/100
4844/4844 [==============================] - 53s 11ms/step - loss: 0.0905 - accuracy: 0.9781
Epoch 60/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0855 - accuracy: 0.9790
Epoch 61/100
4844/4844 [==============================] - 51s 10ms/step - loss: 0.0902 - accuracy: 0.9784
Epoch 62/100
4844/4844 [==============================] - 54s 11ms/step - loss: 0.0890 - accuracy: 0.9784
Epoch 63/100
4844/4844 [==============================] - 52s 11ms/step - loss: 0.0849 - accuracy: 0.9790
Epoch 64/100
4844/4844 [==============================] - 48s 10ms/step - loss: 0.0901 - accuracy: 0.9778
Epoch 65/100
4844/4844 [==============================] - 47s 10ms/step - loss: 0.0882 - accuracy: 0.9791
Epoch 66/100
4844/4844 [==============================] - 47s 10ms/step - loss: 0.0914 - accuracy: 0.9786
Epoch 67/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0852 - accuracy: 0.9797
Epoch 68/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.0890 - accuracy: 0.9785
Epoch 69/100
4844/4844 [==============================] - 53s 11ms/step - loss: 0.0902 - accuracy: 0.9789
Epoch 70/100
4844/4844 [==============================] - 47s 10ms/step - loss: 0.0850 - accuracy: 0.9794
Epoch 71/100
4844/4844 [==============================] - 44s 9ms/step - loss: 0.0902 - accuracy: 0.9787
Epoch 72/100
4844/4844 [==============================] - 44s 9ms/step - loss: 0.0841 - accuracy: 0.9797
Epoch 73/100
4844/4844 [==============================] - 47s 10ms/step - loss: 0.0869 - accuracy: 0.9797
Epoch 74/100
4844/4844 [==============================] - 47s 10ms/step - loss: 0.0884 - accuracy: 0.9793
Epoch 75/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0893 - accuracy: 0.9793
Epoch 76/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.0859 - accuracy: 0.9797
Epoch 77/100
4844/4844 [==============================] - 50s 10ms/step - loss: 0.0851 - accuracy: 0.9801
Epoch 78/100

4844/4844 [==============================] - 49s 10ms/step - loss: 0.0839 - accuracy: 0.9801
Epoch 79/100
4844/4844 [==============================] - 48s 10ms/step - loss: 0.0883 - accuracy: 0.9800
Epoch 80/100
4844/4844 [==============================] - 49s 10ms/step - loss: 0.0852 - accuracy: 0.9802
Epoch 81/100
4844/4844 [==============================] - 48s 10ms/step - loss: 0.0872 - accuracy: 0.9797
Epoch 82/100
4844/4844 [==============================] - 46s 10ms/step - loss: 0.0848 - accuracy: 0.9799
Epoch 83/100
4844/4844 [==============================] - 51s 11ms/step - loss: 0.0805 - accuracy: 0.9810
Epoch 84/100
4844/4844 [==============================] - 52s 11ms/step - loss: 0.0850 - accuracy: 0.9802
Epoch 85/100
4844/4844 [==============================] - 51s 11ms/step - loss: 0.0891 - accuracy: 0.9797
Epoch 86/100
4844/4844 [==============================] - 54s 11ms/step - loss: 0.0857 - accuracy: 0.9802
Epoch 87/100
4844/4844 [==============================] - 56s 12ms/step - loss: 0.0862 - accuracy: 0.9808
Epoch 88/100
4844/4844 [==============================] - 61s 13ms/step - loss: 0.0862 - accuracy: 0.9808
Epoch 89/100
4844/4844 [==============================] - 55s 11ms/step - loss: 0.0889 - accuracy: 0.9803
Epoch 90/100
4844/4844 [==============================] - 60s 12ms/step - loss: 0.0870 - accuracy: 0.9802
Epoch 91/100
4844/4844 [==============================] - 57s 12ms/step - loss: 0.0840 - accuracy: 0.9809
Epoch 92/100
4844/4844 [==============================] - 55s 11ms/step - loss: 0.0889 - accuracy: 0.9802
Epoch 93/100
4844/4844 [==============================] - 54s 11ms/step - loss: 0.0826 - accuracy: 0.9814
Epoch 94/100
4844/4844 [==============================] - 55s 11ms/step - loss: 0.0889 - accuracy: 0.9805
Epoch 95/100
4844/4844 [==============================] - 57s 12ms/step - loss: 0.0793 - accuracy: 0.9814
Epoch 96/100
4844/4844 [==============================] - 56s 12ms/step - loss: 0.0888 - accuracy: 0.9803
Epoch 97/100
4844/4844 [==============================] - 60s 12ms/step - loss: 0.0869 - accuracy: 0.9804
Epoch 98/100
4844/4844 [==============================] - 59s 12ms/step - loss: 0.0873 - accuracy: 0.9808
Epoch 99/100
4844/4844 [==============================] - 57s 12ms/step - loss: 0.0795 - accuracy: 0.9812
Epoch 100/100
4844/4844 [==============================] - 58s 12ms/step - loss: 0.0807 - accuracy: 0.9820

In [16]:
model.save("model_0525.h5")

In [17]:
model = tf.keras.models.load_model('model_0525.h5')

In [18]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)

In [19]:
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
converter.target_spec.supported_types = [tf.float16]
converter.optimizations = [tf.lite.Optimize.DEFAULT]

In [20]:
tflite_model = converter.convert()

INFO:tensorflow:Assets written to: C:\Users\ddang\AppData\Local\Temp\tmpeu7uzdam\assets

WARNING:absl:Buffer deduplication procedure will be skipped when flatbuffer library is not properly loaded

In [21]:
with open('model0525.tflite', 'wb') as f:
    f.write(tflite_model)

In [43]:
k = 10
num_val_samples = len(X) // k
num_epochs = 100
all_scores = []
for i in range(k):
    print('processing fold #', i)

    X_val = X[i * num_val_samples: (i + 1) * num_val_samples]
    y_val = y[i * num_val_samples: (i + 1) * num_val_samples]

    partial_train_data = np.concatenate(
        [X[:i * num_val_samples],
         X[(i + 1) * num_val_samples:]],
        axis=0)
    partial_train_targets = np.concatenate(
        [y[:i * num_val_samples],
         y[(i + 1) * num_val_samples:]],
        axis=0)

    model = build_model()
    model.fit(partial_train_data, partial_train_targets,
              epochs=num_epochs, verbose=0)

    loss, acc = model.evaluate(X_val, y_val, verbose=0)
    all_scores.append(acc)

469/469 [==============================] - 4s 8ms/step - loss: 0.0285 - accuracy: 0.9922
0.9922000169754028